### ISSUE TITLE
  Argus - Shodan Exposure Analyzer

### ISSUE THREAD

**Issue by brother0k** [jasonxtn/Argus#12]
When use: 55. Run All Security Tools
```
Traceback (most recent call last):
  File "/home/user/tools/argus/modules/shodan.py", line 201, in <module>
    main(args.inputs)
  File "/home/user/tools/argus/modules/shodan.py", line 188, in main
    asyncio.run(main_async(inputs))
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/user/tools/argus/modules/shodan.py", line 183, in main_async
    display_shodan_data(result)
  File "/home/user/tools/argus/modules/shodan.py", line 140, in display_shodan_data
    table_stats.add_row(key, value)
  File "/usr/lib/python3/dist-packages/rich/table.py", line 459, in add_row
    raise errors.NotRenderableError(
rich.errors.NotRenderableError: unable to render int; a string or other renderable object is required
[!] Error running shodan.py

```

**Comment by jasonxtn** [comment]
Problem solved. Updated to the latest version.
