### ISSUE TITLE
Shodan

### ISSUE THREAD

**Issue by brother0k** [jasonxtn/Argus#14]
When 300. Run All Security Tools
```
=============================================
Argus - Shodan Exposure Analyzer
=============================================


Traceback (most recent call last):
File "/home/user/tools/argus/modules/shodan.py", line 201, in <module>
main(args.inputs)
File "/home/user/tools/argus/modules/shodan.py", line 188, in main
asyncio.run(main_async(inputs))
File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "/home/user/tools/argus/modules/shodan.py", line 183, in main_async
display_shodan_data(result)
File "/home/user/tools/argus/modules/shodan.py", line 140, in display_shodan_data
table_stats.add_row(key, value)
File "/home/user/tools/argus/path/to/venv/lib/python3.12/site-packages/rich/table.py", line 465, in add_row
raise errors.NotRenderableError(
rich.errors.NotRenderableError: unable to render int; a string or other renderable object is required
[!] Error running shodan.py
```

When 49. Shodan Reconnaissance
```
root@argus:~#: 49
Enter the target domain or URL: example.com

=============================================
Argus - Shodan Exposure Analyzer
=============================================


Traceback (most recent call last):
File "/home/user/tools/argus/modules/shodan.py", line 201, in <module>
main(args.inputs)
File "/home/user/tools/argus/modules/shodan.py", line 188, in main
asyncio.run(main_async(inputs))
File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "/home/user/tools/argus/modules/shodan.py", line 183, in main_async
display_shodan_data(result)
File "/home/user/tools/argus/modules/shodan.py", line 140, in display_shodan_data
table_stats.add_row(key, value)
File "/home/user/tools/argus/path/to/venv/lib/python3.12/site-packages/rich/table.py", line 465, in add_row
raise errors.NotRenderableError(
rich.errors.NotRenderableError: unable to render int; a string or other renderable object is required
[!] Error running shodan.py
TXT report generated successfully: results/example.com/example.com_Shodan_Reconnaissance_20241008_105913.txt
```

Also after fresh install was unauthorized shodan key

**Comment by jasonxtn** [comment]
Problem Fixed !
Update to the latest version.

**Comment by brother0k** [comment]
Awesome. All works! Thanks a lot
