### ISSUE TITLE
16. Traceroute

### ISSUE THREAD

**Issue by brother0k** [jasonxtn/Argus#22]
Traceback (most recent call last):
File "/home/user/tools/argus/modules/traceroute.py", line 14, in <module>
from config.settings import USER_AGENT, DEFAULT_TIMEOUT
ImportError: cannot import name 'USER_AGENT' from 'config.settings' (/home/user/tools/argus/config/settings.py)
[!] Error running traceroute.py
Traceback (most recent call last):
File "/home/user/tools/argus/modules/traceroute.py", line 14, in <module>
from config.settings import USER_AGENT, DEFAULT_TIMEOUT
ImportError: cannot import name 'USER_AGENT' from 'config.settings' (/home/user/tools/argus/config/settings.py)

**Comment by opticaldrive** [comment]
Strange,
https://github.com/jasonxtn/Argus/blob/main/config/settings.py
Seems to exist.

After reviewing the git history, maybe it's possible that you are running on an older version?
Try cloning again.

**Comment by opticaldrive** [comment]
I'm trying out Traceroute, and something seems wrong.
It probably shouldn't be running the email harvesting module.
                            
```                                        
root@argus:~#: 16
Enter the target domain or URL: google.com


=============================================
Argus - Email Harvesting Module
=============================================


[*] Starting email harvesting on http://google.com...
[!] Error crawling google.com: Invalid URL 'google.com': No scheme supplied. Perhaps you meant https://google.com?
[!] No email addresses found.


=============================================
Argus - Email Harvesting Module
=============================================


[*] Starting email harvesting on http://google.com...
[!] Error crawling google.com: Invalid URL 'google.com': No scheme supplied. Perhaps you meant https://google.com?
[!] No email addresses found.

TXT report generated successfully: results/google.com/google.com_Traceroute_20241031_130730.txt
```
